name: Newsfile

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: # Needed for comparison
          fetch-depth: 0
      - name: ":newspaper: Newsfile"
        run: ./scripts/check-newsfragment
